name: Local Assistant
version: 1.0.0
schema: v1
models:
  - name: Nomic Embed
    provider: ollama
    model: nomic-embed-text:latest
    roles:
      - embed
  - name: Autodetect
    provider: ollama
    model: AUTODETECT
    apiBase: http://192.168.5.170:11434
  - name: Qwen 2.5 Coder:32b
    provider: ollama
    model: qwen2.5-coder-32b
    roles:
      - autocomplete
docs:
  - name: Continue
    startUrl: https://docs.continue.dev/intro
    favicon: https://docs.continue.dev/favicon.ico
  - name: NextJS
    startUrl: https://nextjs.org/docs
    favicon: https://nextjs.org/favicon.ico
  - name: ShadCN
    startUrl: https://ui.shadcn.com/docs
    favicon: https://ui.shadcn.com/favicon.ico
  - name: Sanity.io
    startUrl: https://www.sanity.io/docs
    favicon: https://www.sanity.io/favicon.ico
context:
  - provider: code
  - provider: docs
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
  - provider: codebase
